name:                nnhd
version:             0.1.0.0
github:              "cornelius-sevald/nnhd"
license:             BSD3
author:              "Cornelius Sevald-Krause"
maintainer:          "cornelius.sevald@gmail.com"
copyright:           "2020 Cornelius Sevald-Krause"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cornelius-sevald/nnhd#readme>

dependencies:
- base               >= 4.7 && < 5
- random             >= 1.1
- mtl                >= 2.2.2
- vector             >= 0.12.1.2
- hmatrix            >= 0.20.0.0
- normaldistribution >= 1.1.0.3

library:
  source-dirs: src

executables:
  nnhd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nnhd
